paths:
  /login:
    post:
      summary: login
      tags: [Auth]
      description: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: success to login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: internal issues
        '403':
          description: unauthorized
  /register:
    post:
      summary: register
      tags: [Auth]
      description: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                phone:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: success to register
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: internal issues
        '403':
          description: unauthorized
