name: CI-API

on:
  push:
    paths:
      - "api/**"
    branches: [ develop ]
  pull_request:
      branches: [ develop ]

env:
  MONGODB_CONNECTION_STR: ${{ secrets.MONGODB_CONNECTION_STR }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: api
        run: npm install
      - name: Build
        working-directory: api
        run: npm run build --if-present
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: api
        run: npm install
      - name: run Tests
        working-directory: api
        run: npm run test

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: https://pfe-dev.vercel.app/

    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./api #Your Working Directory, Optional
          # alias-domains: | #Optional
          #   staging.angular.vercel-action.amond.dev
          #   pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build --if-present
      - name: Deploy to developement
        run: echo "Deploying to developement api..."
  
  deploy-prod:
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: prod
      url: https://pfe-fares-b.vercel.app/

    if: github.ref == 'refs/heads/master'
    steps:
      # - uses: actions/checkout@v2
      # - name: download a deploy script
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: deployement_zip
      # - name: download a deploy script
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: deployement_script
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build --if-present
      - name: Deploy to production
        run: echo "Deploying to production api..."
  