name: CI-API

on:
  push:
    paths:
      - "api/**"
    branches:
      - develop
      - master
  pull_request:
    paths:
      - "api/**"
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_CONNECTION_STR: ${{ secrets.MONGODB_CONNECTION_STR_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: api
        run: npm install
      - name: Build
        working-directory: api
        run: npm run build --if-present
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      MONGODB_CONNECTION_STR: ${{ secrets.MONGODB_CONNECTION_STR_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: api
        run: npm install
      - name: run Tests
        working-directory: api
        run: npm run test

  vercel-dev:
    needs: test
    if: github.base_ref == 'develop'
    name: "Deploy api to Vercel dev"
    env:
      MONGODB_CONNECTION_STR: ${{ secrets.MONGODB_CONNECTION_STR_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Vercel"
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID_DEV }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_AUTH: ${{ secrets.GRAFANA_AUTH }}
  
  vercel-prod:
    needs: test
    env:
      MONGODB_CONNECTION_STR: ${{ secrets.MONGODB_CONNECTION_STR_PROD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_PROD }}
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    name: "Deploy api to Vercel prod"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Vercel"
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID_PROD }}
          VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_AUTH: ${{ secrets.GRAFANA_AUTH }}
    
      # url: https://pfe-fares-b.vercel.app/
