name: CI-API

on:
  push:
    paths:
      - "api/**"
    branches: [ test ]
  pull_request:
      branches: [ test ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
  test:
    runs-on: self-hosted
    steps:
      - name: Run tests
        run: npm test
  deploy:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build --if-present
      - name: Deploy to production
        run:
          echo "Deploying to production..."
