name: CI-API

on:
  push:
    paths:
      - "api/**"
    branches: [ develop ]
  pull_request:
      branches: [ develop ]

env:
  MONGODB_CONNECTION_STR: ${{ secrets.MONGODB_CONNECTION_STR }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: api
        run: npm install
      - name: Build
        working-directory: api
        run: npm run build --if-present
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        working-directory: api
        run: npm install
      - name: run Tests
        working-directory: api
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build --if-present
      - name: Deploy to production
        run: echo "Deploying to production api..."
      - run: echo $MONGODB_CONNECTION_STR
      - run: echo $JWT_SECRET
