name: CI-WEB

on:
  push:
    paths:
      - "web/**"
    branches:
      - master
      - develop
  pull_request:
    paths:
      - "web/**"
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run Tests
        run: echo "dont have test for web app..."

  deploy-dev:
    needs: test
    if: github.base_ref == 'develop'
    name: "Deploy web to Vercel dev"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish
      uses: netlify/actions/build@master
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
        NETLIFY_BASE: site
        NETLIFY_CMD: npm build
        NETLIFY_DIR: site/web
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_DEV }}
        REACT_APP_BACKEND_BASE_URL: https://pfe-dev.vercel.app/
