name: CI-WEB

on:
  push:
    paths:
      - "web/**"
    branches:
      - master
      - develop
  pull_request:
    paths:
      - "web/**"
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to production web..."

# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#             node-version: ${{ matrix.node-version }}
#       - name: Install dependencies
#         run: npm install
#       - name: Build
#         run: npm run build --if-present

#   deploy:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install dependencies
#         run: npm install
#       - name: Build
#         run: npm run build --if-present
#       - name: Deploy to production
#         run:
#           echo "Deploying to production..."